version: "3.7"

services:
  botvid:
    image: techblog/botvid-19
    container_name: botvid
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - API_KEY=
      - ALLOWED_IDS=
    volumes:
      - ./botvid/config/:/opt/dockerbot/config
